name: CI
on:
  pull_request:
  push:
    branches:
      - main
env:
  otp: "25.0"
  elixir: "1.14.2"
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3
      - name: Install Erlang & Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp }}
          elixir-version: ${{ env.elixir }}
      - uses: actions/cache@v3
        with:
          path: deps
          key: mix-deps-${{ hashFiles('**/mix.lock') }}
      - name: Install mix dependencies
        run: mix deps.get
      - name: Check formatting
        run: mix format --check-formatted
      - name: Check unused deps
        run: mix deps.unlock --check-unused
      - name: Check warnings
        run: mix compile --warnings-as-errors
      - name: Run tests
        run: mix test
